apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-metrics-gap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-metrics-gap
  template:
    metadata:
      labels:
        app: java-metrics-gap
    spec:
      nodeSelector:
        workload: {{ .Values.nodeSelector.workload | quote }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
            - containerPort: 9404
          readinessProbe:
            httpGet:
              path: /status
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /status
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 15
