apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: java-metrics-gap
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: java-metrics-gap
  endpoints:
    - port: metrics
      path: /
      interval: 30s
