apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: exercise-02-java-restart-loop
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: exercise-02
  source:
    repoURL: REPLACE_WITH_GIT_REPO_URL
    targetRevision: HEAD
    path: exercises/02-java-restart-loop/helm
    helm:
      releaseName: exercise-02
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

