image:
  repository: registry.digitalocean.com/devopslabregistry/java-metrics-gap
  tag: 6d36408
  pullPolicy: IfNotPresent

nodeSelector:
  workload: lab

tolerations:
  - key: dedicated
    operator: Equal
    value: lab
    effect: NoSchedule
