image:
  repository: registry.digitalocean.com/devopslabregistry/network-db-connectivity
  tag: 5a1acb2
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: devopslabregistry

db:
  host: db-router.svc.cluster.internal
  port: "13306"
  name: lab
  user: lab_user
  password: change-me

nodeSelector:
  workload: lab

tolerations:
  - key: dedicated
    operator: Equal
    value: lab
    effect: NoSchedule
