image:
  repository: registry.digitalocean.com/devopslabregistry/java-restart-loop
  tag: 5a1acb2
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: devopslabregistry

app:
  windowStart: "2026-13-01T08:00:00Z"

nodeSelector:
  workload: lab

tolerations:
  - key: dedicated
    operator: Equal
    value: lab
    effect: NoSchedule
