apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lane-d
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: exercise-04
  source:
    repoURL: https://github.com/poltorres7/devops-lab-exercices.git
    targetRevision: HEAD
    path: tracks/track-d/helm
    helm:
      releaseName: exercise-04
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
