apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-restart-loop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-restart-loop
  template:
    metadata:
      labels:
        app: java-restart-loop
    spec:
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      nodeSelector:
        workload: {{ .Values.nodeSelector.workload | quote }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: WINDOW_START
              value: {{ .Values.app.windowStart | quote }}
          ports:
            - containerPort: 8080
