apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-ci-failure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-ci-failure
  template:
    metadata:
      labels:
        app: java-ci-failure
    spec:
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      nodeSelector:
        workload: {{ .Values.nodeSelector.workload | quote }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 15
