apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: exercise-03-java-resource-starvation
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: exercise-03
  source:
    repoURL: REPLACE_WITH_GIT_REPO_URL
    targetRevision: HEAD
    path: exercises/03-java-resource-starvation/helm
    helm:
      releaseName: exercise-03
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

