image:
  repository: registry.digitalocean.com/devopslabregistry/java-metrics-gap
  tag: bf79f34
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: devopslabregistry

nodeSelector:
  workload: lab

tolerations:
  - key: dedicated
    operator: Equal
    value: lab
    effect: NoSchedule
