image:
  repository: registry.digitalocean.com/devopslabregistry/java-metrics-gap
  tag: 503acce
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: devopslabregistry

nodeSelector:
  workload: lab

tolerations:
  - key: dedicated
    operator: Equal
    value: lab
    effect: NoSchedule
