image:
  repository: registry.digitalocean.com/devopslabregistry/java-ci-failure
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: devopslabregistry

nodeSelector:
  workload: lab

tolerations:
  - key: dedicated
    operator: Equal
    value: lab
    effect: NoSchedule
